behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters: 
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0
      beta: 0
      epsilon: 0
      lambd: 0
    network_settings: 
      normalize: False
      hidden_units: 256
      num_layers: 2
    reward_signals: 
      extrinsic: 
        gamma: 0.99
        strength: 0
        network_settings: 
          normalize: False
          hidden_units: 128
          num_layers: 2
    checkpoint_interval: 500000
    max_steps: 2000000
    time_horizon: 128
    summary_freq: 20000